### ISSUE TITLE
Test on Lines 33-36 of spec requires hard-coding of variable to pass

### ISSUE THREAD

**Issue by mjfender** [learn-co-curriculum/sinatra-view-and-controller-readme-walkthrough#10]
Had to hard-code the @friends variable in this lab in order to get the test to pass. This was due to no scope access. XOxO, Matt and @clintonn

@friends = ["Charlie Chaplin", "Richard Pryor", "Eddie Murphy", "Louis CK", "Jerry Seinfeld"]

**Comment by gj** [comment]
Hey @mjfender !

Looks like this was already taken care of in an earlier PR. 🙂 

Thanks for contributing!
